---
- name: Set Ip loopback
  hosts: all
  gather_fact: no

  tasks:
    - name: Set loopback IPv4 address
      ios_13_interface:
        name: "{{item.Name}}"
        ipv4: "{{item.aadr}}"
        state: present
      with_items:
        - {Name: "loopback 1", addr: "10.0.1.1/24"}
        - {Name: "loopback 2", addr: "10.0.1.2/24"}
        - {Name: "loopback 3", addr: "10.0.1.3/24"}
        
